In [20]:
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [6]:
boston = pd.read_csv('../../Datasets/Boston.csv')
X = boston.drop('medv', axis=1)
y = boston['medv']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=25)

In [36]:
alphas = np.arange(0.001, 10.001, 0.01)

In [37]:
rmses = {}
maes = {}
r2s = {}
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    # error = root_mean_squared_error(y_test, y_pred)
    rmses[a] = root_mean_squared_error(y_test, y_pred)
    maes[a] = mean_absolute_error(y_test, y_pred)
    r2s[a] = r2_score(y_test, y_pred)
    # print(f'alpha = {a}, error = {error}')

In [38]:
print('rmse min ', min(rmses, key=rmses.get))
print('mae min ', min(maes, key=maes.get))
print('r2 min ', max(r2s, key=r2s.get))

rmse min  0.25099999999999995
mae min  0.7709999999999999
r2 min  0.25099999999999995

Lasso

In [49]:
rmses = {}
maes = {}
r2s = {}
for a in alphas:
    lasso = Lasso(alpha=a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    rmses[a] = root_mean_squared_error(y_test, y_pred)
    maes[a] = mean_absolute_error(y_test, y_pred)
    r2s[a] = r2_score(y_test, y_pred)

In [50]:
print('rmse min ', min(rmses, key=rmses.get))
print('mae min ', min(maes, key=maes.get))
print('r2 min ', max(r2s, key=r2s.get))

rmse min  0.001
mae min  0.020999999999999998
r2 min  0.001

In [51]:
maes[0.020999999999999998]

3.0734023778055977

elastic net

In [ ]:
rmses = {}
maes = {}
r2s = {}
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2, 2.5, 5, 10]
ratios = [0.001, 0.25, 0.5, 0.75, 1]
scores = []
for a in alphas:
    for r in ratios:
        en = ElasticNet(alpha=a, l1_ratio=r)
        en.fit(X_train, y_train)
        y_pred = en.predict(X_test)
        scores.append([a, r, root_mean_squared_error(y_test, y_pred)])

d = pd.DataFrame(scores, columns=['alpha', 'l1_ratio', 'rmse'])
d.sort_values('rmse')

     alpha  l1_ratio      rmse
0    0.001     0.001  4.643477
1    0.001     0.250  4.643494
2    0.001     0.500  4.644058
3    0.001     0.750  4.645431
4    0.001     1.000  4.648000
9    0.010     1.000  4.658083
8    0.010     0.750  4.666774
7    0.010     0.500  4.675507
6    0.010     0.250  4.680518
5    0.010     0.001  4.683301
10   0.100     0.001  4.739351
11   0.100     0.250  4.750335
13   0.100     0.750  4.751158
14   0.100     1.000  4.751875
12   0.100     0.500  4.752147
19   0.500     1.000  4.762565
18   0.500     0.750  4.802971
17   0.500     0.500  4.833524
16   0.500     0.250  4.855667
15   0.500     0.001  4.865316
24   1.000     1.000  4.910966
23   1.000     0.750  4.929641
22   1.000     0.500  4.939145
21   1.000     0.250  4.947776
20   1.000     0.001  4.952033
25   1.500     0.001  5.009703
26   1.500     0.250  5.014760
27   1.500     0.500  5.026610
30   2.000     0.001  5.055768
28   1.500     0.750  5.059472
31   2.000     0.250  5.070914
35   2.500     0.001  5.095834
32   2.000     0.500  5.104496
36   2.500     0.250  5.121585
29   1.500     1.000  5.137841
37   2.500     0.500  5.177256
33   2.000     0.750  5.179923
34   2.000     1.000  5.216336
38   2.500     0.750  5.245330
40   5.000     0.001  5.257260
39   2.500     1.000  5.325815
41   5.000     0.250  5.341743
42   5.000     0.500  5.472585
45  10.000     0.001  5.501386
43   5.000     0.750  5.595680
44   5.000     1.000  5.685901
46  10.000     0.250  5.697862
47  10.000     0.500  5.875953
48  10.000     0.750  5.943684
49  10.000     1.000  6.033508

In [46]:
print('rmse min ', min(rmses, key=rmses.get))
print('mae min ', min(maes, key=maes.get))
print('r2 min ', max(r2s, key=r2s.get))

rmse min  0.001
mae min  0.001
r2 min  0.001

In [48]:
maes[0.001]

3.941862960398445