In [7]:
import pandas as pd
import numpy as np
from sklearn.metrics import log_loss, classification_report, f1_score
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [ ]:
wisconsin = pd.read_csv("../Datasets/cases/Wisconsin/BreastCancer.csv", index_col=0)

In [11]:
from sklearn.pipeline import Pipeline

X = wisconsin.drop('Class', axis=1)
y = wisconsin['Class']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=25)

svm = SVC()

scores = []
Cs = np.linspace(1e-3, 5, 20)
for c in Cs:
    pipe = Pipeline(
    [('SVM',SVC(kernel='linear', C=c))])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)

    scores.append([c,f1_score(y_test,y_pred, pos_label='Malignant')])

scores = pd.DataFrame(scores, columns=['C','F1'])
scores.sort_values('F1', ascending=False)

           C        F1
1   0.264105  0.936709
2   0.527211  0.936709
3   0.790316  0.936709
4   1.053421  0.936709
12  3.158263  0.936709
5   1.316526  0.936709
6   1.579632  0.936709
7   1.842737  0.936709
8   2.105842  0.936709
9   2.368947  0.936709
10  2.632053  0.936709
11  2.895158  0.936709
16  4.210684  0.936709
13  3.421368  0.936709
14  3.684474  0.936709
15  3.947579  0.936709
18  4.736895  0.936709
17  4.473789  0.936709
19  5.000000  0.936709
0   0.001000  0.923077